/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.23
 * Generated at: 2026-06-29 06:23:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>Dashboard | ShopSphere Admin</title>\n");
      out.write("  <style>\n");
      out.write("    :root { --bg:#08111f; --panel:rgba(10,19,35,.9); --line:rgba(255,255,255,.08); --text:#e7eff9; --muted:#8fa4bc; --accent:#0ea5e9; --accent-2:#22c55e; --accent-3:#f97316; --accent-4:#facc15; }\n");
      out.write("    * { box-sizing: border-box; }\n");
      out.write("    body {\n");
      out.write("      margin: 0;\n");
      out.write("      min-height: 100vh;\n");
      out.write("      font-family: \"Segoe UI\", Arial, sans-serif;\n");
      out.write("      color: var(--text);\n");
      out.write("      background:\n");
      out.write("        radial-gradient(circle at top left, rgba(14,165,233,.16), transparent 28%),\n");
      out.write("        radial-gradient(circle at top right, rgba(34,197,94,.12), transparent 25%),\n");
      out.write("        linear-gradient(180deg, #08111f 0%, #0b1424 100%);\n");
      out.write("    }\n");
      out.write("    a { color: inherit; text-decoration: none; }\n");
      out.write("    .layout {\n");
      out.write("      display: grid;\n");
      out.write("      grid-template-columns: 280px 1fr;\n");
      out.write("      min-height: 100vh;\n");
      out.write("    }\n");
      out.write("    .sidebar {\n");
      out.write("      position: sticky;\n");
      out.write("      top: 0;\n");
      out.write("      height: 100vh;\n");
      out.write("      padding: 24px;\n");
      out.write("      border-right: 1px solid var(--line);\n");
      out.write("      background: rgba(7,17,31,.72);\n");
      out.write("      backdrop-filter: blur(18px);\n");
      out.write("    }\n");
      out.write("    .brand {\n");
      out.write("      display: flex;\n");
      out.write("      align-items: center;\n");
      out.write("      gap: 10px;\n");
      out.write("      font-size: 26px;\n");
      out.write("      font-weight: 900;\n");
      out.write("      color: #fff;\n");
      out.write("    }\n");
      out.write("    .mark {\n");
      out.write("      width: 36px;\n");
      out.write("      height: 36px;\n");
      out.write("      border-radius: 11px;\n");
      out.write("      display: grid;\n");
      out.write("      place-items: center;\n");
      out.write("      background: linear-gradient(135deg, var(--accent), var(--accent-2));\n");
      out.write("    }\n");
      out.write("    .menu { list-style: none; padding: 18px 0 0; margin: 0; display: grid; gap: 8px; }\n");
      out.write("    .menu a {\n");
      out.write("      display: flex;\n");
      out.write("      align-items: center;\n");
      out.write("      min-height: 46px;\n");
      out.write("      padding: 0 14px;\n");
      out.write("      border-radius: 14px;\n");
      out.write("      color: #c9d6e6;\n");
      out.write("      font-weight: 800;\n");
      out.write("      background: transparent;\n");
      out.write("      border: 1px solid transparent;\n");
      out.write("    }\n");
      out.write("    .menu a.active,\n");
      out.write("    .menu a:hover {\n");
      out.write("      background: rgba(255,255,255,.06);\n");
      out.write("      color: #fff;\n");
      out.write("      border-color: rgba(255,255,255,.08);\n");
      out.write("    }\n");
      out.write("    .sidebar-note {\n");
      out.write("      margin-top: 18px;\n");
      out.write("      padding-top: 18px;\n");
      out.write("      border-top: 1px solid var(--line);\n");
      out.write("      color: var(--muted);\n");
      out.write("      line-height: 1.7;\n");
      out.write("      font-size: 13px;\n");
      out.write("    }\n");
      out.write("    .content {\n");
      out.write("      padding: 24px;\n");
      out.write("    }\n");
      out.write("    .topbar {\n");
      out.write("      display: flex;\n");
      out.write("      justify-content: space-between;\n");
      out.write("      align-items: center;\n");
      out.write("      gap: 18px;\n");
      out.write("      padding: 18px 22px;\n");
      out.write("      border-radius: 22px;\n");
      out.write("      border: 1px solid var(--line);\n");
      out.write("      background: var(--panel);\n");
      out.write("      box-shadow: 0 24px 60px rgba(0,0,0,.22);\n");
      out.write("    }\n");
      out.write("    .topbar h1 { margin: 0; font-size: 30px; }\n");
      out.write("    .topbar p { margin: 6px 0 0; color: var(--muted); }\n");
      out.write("    .actions { display: flex; gap: 10px; flex-wrap: wrap; }\n");
      out.write("    .btn {\n");
      out.write("      display: inline-flex;\n");
      out.write("      align-items: center;\n");
      out.write("      justify-content: center;\n");
      out.write("      min-height: 46px;\n");
      out.write("      padding: 0 16px;\n");
      out.write("      border-radius: 14px;\n");
      out.write("      border: 0;\n");
      out.write("      cursor: pointer;\n");
      out.write("      font-weight: 900;\n");
      out.write("      transition: transform .2s;\n");
      out.write("    }\n");
      out.write("    .btn:hover { transform: translateY(-2px); }\n");
      out.write("    .btn-primary { background: linear-gradient(135deg, var(--accent), var(--accent-2)); color: #fff; }\n");
      out.write("    .btn-secondary { background: rgba(255,255,255,.06); color: #fff; border: 1px solid var(--line); }\n");
      out.write("    .stats {\n");
      out.write("      display: grid;\n");
      out.write("      grid-template-columns: repeat(4, minmax(0, 1fr));\n");
      out.write("      gap: 18px;\n");
      out.write("      margin-top: 18px;\n");
      out.write("    }\n");
      out.write("    .card {\n");
      out.write("      padding: 20px;\n");
      out.write("      border-radius: 22px;\n");
      out.write("      border: 1px solid var(--line);\n");
      out.write("      background: var(--panel);\n");
      out.write("      box-shadow: 0 18px 42px rgba(0,0,0,.18);\n");
      out.write("    }\n");
      out.write("    .card .label {\n");
      out.write("      color: var(--muted);\n");
      out.write("      font-size: 12px;\n");
      out.write("      font-weight: 900;\n");
      out.write("      letter-spacing: .12em;\n");
      out.write("      text-transform: uppercase;\n");
      out.write("    }\n");
      out.write("    .card .value {\n");
      out.write("      margin-top: 10px;\n");
      out.write("      color: #fff;\n");
      out.write("      font-size: 34px;\n");
      out.write("      font-weight: 900;\n");
      out.write("      line-height: 1;\n");
      out.write("    }\n");
      out.write("    .card .note { margin-top: 10px; color: #bfd0e4; line-height: 1.6; font-size: 13px; }\n");
      out.write("    .grid {\n");
      out.write("      display: grid;\n");
      out.write("      grid-template-columns: 1.2fr .8fr;\n");
      out.write("      gap: 18px;\n");
      out.write("      margin-top: 18px;\n");
      out.write("    }\n");
      out.write("    .section-head {\n");
      out.write("      display: flex;\n");
      out.write("      justify-content: space-between;\n");
      out.write("      align-items: end;\n");
      out.write("      gap: 16px;\n");
      out.write("      margin-bottom: 16px;\n");
      out.write("    }\n");
      out.write("    .section-head h2 { margin: 0; font-size: 24px; color: #fff; }\n");
      out.write("    .section-head p { margin: 6px 0 0; color: var(--muted); }\n");
      out.write("    .list {\n");
      out.write("      display: grid;\n");
      out.write("      gap: 12px;\n");
      out.write("      margin: 0;\n");
      out.write("      padding: 0;\n");
      out.write("      list-style: none;\n");
      out.write("    }\n");
      out.write("    .list li {\n");
      out.write("      display: flex;\n");
      out.write("      justify-content: space-between;\n");
      out.write("      gap: 12px;\n");
      out.write("      padding: 14px 16px;\n");
      out.write("      border-radius: 14px;\n");
      out.write("      background: rgba(255,255,255,.04);\n");
      out.write("      border: 1px solid rgba(255,255,255,.06);\n");
      out.write("      color: #dbe7f5;\n");
      out.write("    }\n");
      out.write("    .pill {\n");
      out.write("      display: inline-flex;\n");
      out.write("      align-items: center;\n");
      out.write("      min-height: 28px;\n");
      out.write("      padding: 0 10px;\n");
      out.write("      border-radius: 999px;\n");
      out.write("      background: rgba(14,165,233,.12);\n");
      out.write("      color: #8bdcff;\n");
      out.write("      font-size: 12px;\n");
      out.write("      font-weight: 900;\n");
      out.write("    }\n");
      out.write("    .activity {\n");
      out.write("      display: grid;\n");
      out.write("      gap: 12px;\n");
      out.write("    }\n");
      out.write("    .activity .row {\n");
      out.write("      padding: 14px 16px;\n");
      out.write("      border-radius: 14px;\n");
      out.write("      background: rgba(255,255,255,.04);\n");
      out.write("      border: 1px solid rgba(255,255,255,.06);\n");
      out.write("      color: #dbe7f5;\n");
      out.write("      line-height: 1.6;\n");
      out.write("    }\n");
      out.write("    .mobile-toggle { display: none; }\n");
      out.write("    @media (max-width: 1020px) {\n");
      out.write("      .layout { grid-template-columns: 1fr; }\n");
      out.write("      .sidebar { position: static; height: auto; }\n");
      out.write("      .stats, .grid { grid-template-columns: 1fr 1fr; }\n");
      out.write("    }\n");
      out.write("    @media (max-width: 760px) {\n");
      out.write("      .content { padding: 16px; }\n");
      out.write("      .stats, .grid { grid-template-columns: 1fr; }\n");
      out.write("      .topbar { flex-direction: column; align-items: flex-start; }\n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"layout\">\n");
      out.write("  <aside class=\"sidebar\">\n");
      out.write("    <a class=\"brand\" href=\"");
      out.print(request.getContextPath());
      out.write("/index.html\">\n");
      out.write("      <span class=\"mark\">S</span>\n");
      out.write("      <span>ShopSphere</span>\n");
      out.write("    </a>\n");
      out.write("    <ul class=\"menu\">\n");
      out.write("      <li><a class=\"active\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/adminDashboard\">Dashboard</a></li>\n");
      out.write("      <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/adminProducts\">Products</a></li>\n");
      out.write("      <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/addProduct\">Add Product</a></li>\n");
      out.write("      <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/index.html\">Storefront</a></li>\n");
      out.write("    </ul>\n");
      out.write("    <div class=\"sidebar-note\">\n");
      out.write("      Manage products and inventory from one focused control panel.\n");
      out.write("    </div>\n");
      out.write("  </aside>\n");
      out.write("\n");
      out.write("  <main class=\"content\">\n");
      out.write("    <header class=\"topbar\">\n");
      out.write("      <div>\n");
      out.write("        <div class=\"pill\">Admin dashboard</div>\n");
      out.write("        <h1>Welcome back, ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.admin}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\n");
      out.write("        <p>Here is the current state of your store.</p>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"actions\">\n");
      out.write("        <a class=\"btn btn-secondary\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/adminProducts\">View products</a>\n");
      out.write("        <a class=\"btn btn-primary\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/addProduct\">Add product</a>\n");
      out.write("      </div>\n");
      out.write("    </header>\n");
      out.write("\n");
      out.write("    <section class=\"stats\">\n");
      out.write("      <div class=\"card\">\n");
      out.write("        <div class=\"label\">Products</div>\n");
      out.write("        <div class=\"value\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${products}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("        <div class=\"note\">Current catalog items in the store.</div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"card\">\n");
      out.write("        <div class=\"label\">Users</div>\n");
      out.write("        <div class=\"value\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${users}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("        <div class=\"note\">Registered customer accounts.</div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"card\">\n");
      out.write("        <div class=\"label\">Orders</div>\n");
      out.write("        <div class=\"value\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orders}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("        <div class=\"note\">Total order records currently tracked.</div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"card\">\n");
      out.write("        <div class=\"label\">Revenue</div>\n");
      out.write("        <div class=\"value\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${revenue}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("        <div class=\"note\">Gross revenue snapshot from the system.</div>\n");
      out.write("      </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <section class=\"grid\">\n");
      out.write("      <div class=\"card\">\n");
      out.write("        <div class=\"section-head\">\n");
      out.write("          <div>\n");
      out.write("            <h2>Quick actions</h2>\n");
      out.write("            <p>Tasks used most often by the admin flow.</p>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <ul class=\"list\">\n");
      out.write("          <li><span>Review catalog updates</span><span class=\"pill\">Products</span></li>\n");
      out.write("          <li><span>Add a new product listing</span><span class=\"pill\">Add</span></li>\n");
      out.write("          <li><span>Edit pricing or inventory</span><span class=\"pill\">Update</span></li>\n");
      out.write("          <li><span>Return to storefront</span><span class=\"pill\">Store</span></li>\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"card\">\n");
      out.write("        <div class=\"section-head\">\n");
      out.write("          <div>\n");
      out.write("            <h2>Store notes</h2>\n");
      out.write("            <p>Operational summary for this admin session.</p>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"activity\">\n");
      out.write("          <div class=\"row\">Inventory and product management are linked to the existing servlet routes.</div>\n");
      out.write("          <div class=\"row\">The storefront and admin views now share the same visual language.</div>\n");
      out.write("          <div class=\"row\">Use the product pages to keep catalog content current.</div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </section>\n");
      out.write("  </main>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
