/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.23
 * Generated at: 2026-06-29 06:23:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>Admin Login | ShopSphere</title>\n");
      out.write("  <style>\n");
      out.write("    :root { --bg:#08111f; --panel:rgba(10,19,35,.9); --line:rgba(255,255,255,.08); --text:#e7eff9; --muted:#8fa4bc; --accent:#0ea5e9; --accent-2:#22c55e; }\n");
      out.write("    * { box-sizing: border-box; }\n");
      out.write("    body {\n");
      out.write("      margin: 0;\n");
      out.write("      min-height: 100vh;\n");
      out.write("      display: grid;\n");
      out.write("      place-items: center;\n");
      out.write("      font-family: \"Segoe UI\", Arial, sans-serif;\n");
      out.write("      color: var(--text);\n");
      out.write("      background:\n");
      out.write("        radial-gradient(circle at top left, rgba(14,165,233,.18), transparent 28%),\n");
      out.write("        radial-gradient(circle at top right, rgba(34,197,94,.12), transparent 24%),\n");
      out.write("        linear-gradient(180deg, #08111f 0%, #0b1424 100%);\n");
      out.write("    }\n");
      out.write("    .wrap {\n");
      out.write("      width: min(1100px, calc(100% - 32px));\n");
      out.write("      display: grid;\n");
      out.write("      grid-template-columns: 0.95fr 1.05fr;\n");
      out.write("      gap: 18px;\n");
      out.write("    }\n");
      out.write("    .panel {\n");
      out.write("      border-radius: 24px;\n");
      out.write("      border: 1px solid var(--line);\n");
      out.write("      background: var(--panel);\n");
      out.write("      box-shadow: 0 24px 60px rgba(0,0,0,.24);\n");
      out.write("      overflow: hidden;\n");
      out.write("    }\n");
      out.write("    .hero {\n");
      out.write("      padding: 38px;\n");
      out.write("      min-height: 560px;\n");
      out.write("      display: flex;\n");
      out.write("      flex-direction: column;\n");
      out.write("      justify-content: space-between;\n");
      out.write("      background:\n");
      out.write("        linear-gradient(180deg, rgba(8,17,31,.14), rgba(8,17,31,.92)),\n");
      out.write("        url(\"images/products/24-jbl-speaker.webp\") center/cover;\n");
      out.write("    }\n");
      out.write("    .brand {\n");
      out.write("      display: inline-flex;\n");
      out.write("      align-items: center;\n");
      out.write("      gap: 10px;\n");
      out.write("      color: #fff;\n");
      out.write("      font-size: 28px;\n");
      out.write("      font-weight: 900;\n");
      out.write("      text-decoration: none;\n");
      out.write("    }\n");
      out.write("    .mark {\n");
      out.write("      width: 36px;\n");
      out.write("      height: 36px;\n");
      out.write("      border-radius: 11px;\n");
      out.write("      display: grid;\n");
      out.write("      place-items: center;\n");
      out.write("      background: linear-gradient(135deg, var(--accent), var(--accent-2));\n");
      out.write("    }\n");
      out.write("    .hero h1 {\n");
      out.write("      margin: 0;\n");
      out.write("      max-width: 11ch;\n");
      out.write("      font-size: clamp(38px, 5vw, 62px);\n");
      out.write("      line-height: .96;\n");
      out.write("    }\n");
      out.write("    .hero p {\n");
      out.write("      margin: 18px 0 0;\n");
      out.write("      max-width: 40ch;\n");
      out.write("      color: #c8d7ea;\n");
      out.write("      line-height: 1.75;\n");
      out.write("    }\n");
      out.write("    .chips { display: flex; flex-wrap: wrap; gap: 10px; margin-top: 28px; }\n");
      out.write("    .chip {\n");
      out.write("      display: inline-flex;\n");
      out.write("      align-items: center;\n");
      out.write("      min-height: 34px;\n");
      out.write("      padding: 0 12px;\n");
      out.write("      border-radius: 999px;\n");
      out.write("      background: rgba(255,255,255,.08);\n");
      out.write("      border: 1px solid rgba(255,255,255,.08);\n");
      out.write("      color: #fff;\n");
      out.write("      font-size: 12px;\n");
      out.write("      font-weight: 800;\n");
      out.write("    }\n");
      out.write("    .form {\n");
      out.write("      padding: 38px;\n");
      out.write("    }\n");
      out.write("    .eyebrow {\n");
      out.write("      display: inline-flex;\n");
      out.write("      align-items: center;\n");
      out.write("      min-height: 34px;\n");
      out.write("      padding: 0 12px;\n");
      out.write("      border-radius: 999px;\n");
      out.write("      background: rgba(14,165,233,.12);\n");
      out.write("      color: #8bdcff;\n");
      out.write("      font-size: 12px;\n");
      out.write("      font-weight: 900;\n");
      out.write("      letter-spacing: .12em;\n");
      out.write("      text-transform: uppercase;\n");
      out.write("    }\n");
      out.write("    h2 { margin: 14px 0 8px; font-size: 34px; }\n");
      out.write("    .sub { margin: 0 0 24px; color: var(--muted); line-height: 1.65; }\n");
      out.write("    .alert {\n");
      out.write("      display: flex;\n");
      out.write("      gap: 10px;\n");
      out.write("      align-items: flex-start;\n");
      out.write("      margin-bottom: 18px;\n");
      out.write("      padding: 14px 16px;\n");
      out.write("      border-radius: 14px;\n");
      out.write("      background: rgba(249,115,22,.12);\n");
      out.write("      border: 1px solid rgba(249,115,22,.18);\n");
      out.write("      color: #ffcfb5;\n");
      out.write("    }\n");
      out.write("    form { display: grid; gap: 18px; }\n");
      out.write("    .field { display: grid; gap: 8px; }\n");
      out.write("    label { color: #d8e4f2; font-size: 13px; font-weight: 800; }\n");
      out.write("    input {\n");
      out.write("      min-height: 50px;\n");
      out.write("      padding: 0 16px;\n");
      out.write("      border-radius: 14px;\n");
      out.write("      border: 1px solid rgba(255,255,255,.1);\n");
      out.write("      background: rgba(255,255,255,.04);\n");
      out.write("      color: #fff;\n");
      out.write("      outline: none;\n");
      out.write("    }\n");
      out.write("    input:focus {\n");
      out.write("      border-color: rgba(14,165,233,.7);\n");
      out.write("      box-shadow: 0 0 0 4px rgba(14,165,233,.14);\n");
      out.write("    }\n");
      out.write("    .btn {\n");
      out.write("      display: inline-flex;\n");
      out.write("      align-items: center;\n");
      out.write("      justify-content: center;\n");
      out.write("      min-height: 50px;\n");
      out.write("      padding: 0 18px;\n");
      out.write("      border-radius: 14px;\n");
      out.write("      border: 0;\n");
      out.write("      cursor: pointer;\n");
      out.write("      font-size: 15px;\n");
      out.write("      font-weight: 900;\n");
      out.write("      background: linear-gradient(135deg, var(--accent), var(--accent-2));\n");
      out.write("      color: #fff;\n");
      out.write("      transition: transform .2s;\n");
      out.write("    }\n");
      out.write("    .btn:hover { transform: translateY(-2px); }\n");
      out.write("    .footer {\n");
      out.write("      margin-top: 18px;\n");
      out.write("      padding-top: 18px;\n");
      out.write("      border-top: 1px solid var(--line);\n");
      out.write("      color: var(--muted);\n");
      out.write("      font-size: 13px;\n");
      out.write("      line-height: 1.7;\n");
      out.write("    }\n");
      out.write("    .footer strong { color: #fff; }\n");
      out.write("    .toggle {\n");
      out.write("      align-self: end;\n");
      out.write("      border: 0;\n");
      out.write("      background: transparent;\n");
      out.write("      color: #8bdcff;\n");
      out.write("      cursor: pointer;\n");
      out.write("      font-weight: 800;\n");
      out.write("      padding: 0;\n");
      out.write("    }\n");
      out.write("    @media (max-width: 980px) {\n");
      out.write("      .wrap { grid-template-columns: 1fr; }\n");
      out.write("      .hero { min-height: 360px; }\n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"wrap\">\n");
      out.write("  <section class=\"panel hero\">\n");
      out.write("    <div>\n");
      out.write("      <a class=\"brand\" href=\"index.html\">\n");
      out.write("        <span class=\"mark\">S</span>\n");
      out.write("        <span>ShopSphere</span>\n");
      out.write("      </a>\n");
      out.write("      <h1>Admin control for a cleaner storefront.</h1>\n");
      out.write("      <p>Manage products, inventory, and order-facing content through a focused dashboard designed for everyday operations.</p>\n");
      out.write("      <div class=\"chips\">\n");
      out.write("        <span class=\"chip\">Product management</span>\n");
      out.write("        <span class=\"chip\">Inventory control</span>\n");
      out.write("        <span class=\"chip\">Order visibility</span>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </section>\n");
      out.write("\n");
      out.write("  <section class=\"panel form\">\n");
      out.write("    <div class=\"eyebrow\">Admin access</div>\n");
      out.write("    <h2>Sign in</h2>\n");
      out.write("    <p class=\"sub\">Enter the administrator credentials to continue.</p>\n");
      out.write("\n");
      out.write("    ");

      String error = (String) request.getAttribute("error");
      if (error != null) {
    
      out.write("\n");
      out.write("    <div class=\"alert\"><span>!</span><span>");
      out.print( error );
      out.write("</span></div>\n");
      out.write("    ");

      }
    
      out.write("\n");
      out.write("\n");
      out.write("    <form action=\"adminLogin\" method=\"post\" id=\"adminLoginForm\">\n");
      out.write("      <div class=\"field\">\n");
      out.write("        <label for=\"username\">Username</label>\n");
      out.write("        <input class=\"form-control\" type=\"text\" id=\"username\" name=\"username\" placeholder=\"Enter your username\" required autocomplete=\"username\">\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"field\">\n");
      out.write("        <label for=\"password\">Password</label>\n");
      out.write("        <input class=\"form-control\" type=\"password\" id=\"password\" name=\"password\" placeholder=\"Enter your password\" required autocomplete=\"current-password\">\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <button type=\"button\" class=\"toggle\" id=\"togglePassword\">Show password</button>\n");
      out.write("      <button type=\"submit\" class=\"btn\">Sign in to dashboard</button>\n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("    <div class=\"footer\">\n");
      out.write("      <strong>ShopSphere</strong> admin console.\n");
      out.write("    </div>\n");
      out.write("  </section>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("(function () {\n");
      out.write("  const input = document.getElementById(\"password\");\n");
      out.write("  const toggle = document.getElementById(\"togglePassword\");\n");
      out.write("  toggle.addEventListener(\"click\", function () {\n");
      out.write("    const isHidden = input.type === \"password\";\n");
      out.write("    input.type = isHidden ? \"text\" : \"password\";\n");
      out.write("    toggle.textContent = isHidden ? \"Hide password\" : \"Show password\";\n");
      out.write("  });\n");
      out.write("})();\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
